<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0w97keW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0w97keW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0w97keW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0w97keW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0w97keW\App_KernelDevDebugContainer([
    'container.build_hash' => '0w97keW',
    'container.build_id' => 'ffae33f5',
    'container.build_time' => 1678376065,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0w97keW');
