<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRWXFfRO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRWXFfRO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRWXFfRO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRWXFfRO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRWXFfRO\App_KernelDevDebugContainer([
    'container.build_hash' => 'RWXFfRO',
    'container.build_id' => '6d782047',
    'container.build_time' => 1678559784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRWXFfRO');
