<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP8lOPsQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP8lOPsQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP8lOPsQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP8lOPsQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP8lOPsQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'P8lOPsQ',
    'container.build_id' => '87102f76',
    'container.build_time' => 1678381083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP8lOPsQ');
