<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\RacineController::index'], [], [['text', '/']], [], [], []],
    'app_accueil' => [[], ['_controller' => 'App\\Controller\\RacineController::accueil'], [], [['text', '/accueil']], [], [], []],
    'app_connexion' => [[], ['_controller' => 'App\\Controller\\RacineController::signin'], [], [['text', '/signin']], [], [], []],
    'app_incription' => [[], ['_controller' => 'App\\Controller\\RacineController::register'], [], [['text', '/signup']], [], [], []],
    'app_moncompte' => [[], ['_controller' => 'App\\Controller\\RacineController::account'], [], [['text', '/moncompte']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityAdminController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityAdminController::logout'], [], [['text', '/logout']], [], [], []],
    'app_login_user' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/loginuser']], [], [], []],
    'app_user_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logoutuser']], [], [], []],
    'app_sondages_index' => [[], ['_controller' => 'App\\Controller\\SondagesController::index'], [], [['text', '/sondages/']], [], [], []],
    'app_sondages_new' => [[], ['_controller' => 'App\\Controller\\SondagesController::new'], [], [['text', '/sondages/new']], [], [], []],
    'app_sondages_show' => [['id'], ['_controller' => 'App\\Controller\\SondagesController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/sondages']], [], [], []],
    'app_sondages_edit' => [['id'], ['_controller' => 'App\\Controller\\SondagesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/sondages']], [], [], []],
    'app_sondages_delete' => [['id'], ['_controller' => 'App\\Controller\\SondagesController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/sondages']], [], [], []],
    'app_creation' => [[], ['_controller' => 'App\\Controller\\SondagesController::answer'], [], [['text', '/sondages/repondre']], [], [], []],
];
